projects.json

This PR adds two of our missing projects to the list.

Update projects.json to add ozzie and tlint

---

projects.json

Per #5, this PR updates the list of maintainers for our projects.

Update list of maintainers

---

resources/views/dashboard.blade.php

Whenever I'm using Ozzie I'm opening all links in a new tab, figured I'd make it easier.

Open all links in a new tab

---

projects.json

Add newer open source projects to Ozzie

---

projects.json

This PR updates `projects.json` with the latest project maintainers.

Update project maintainers

---

composer.json
composer.lock

This pull request updates the `graham-campbell/github` package to version 8.6 in order to use the updated github auth change.

Update Graham-Campbell Package

---

app/Notifications/SendOzzieStats.php

I'm so sorry; I would have made this part of my other PR but only realised it after the fact.

Consistency with console & web output

---

resources/views/components/debt-table.blade.php

Made the Pull request column more descriptive by changing the case.

Change case of table row

---

resources/views/components/debt-table.blade.php
resources/views/components/project.blade.php
resources/views/svg/link.blade.php

This changes the anchor links to `#{namespace}-{name}`. Also added an icon before each row.

Changed anchorlink to namespace + name and added icon

---

README.md
app/Http/Controllers/Api/ProjectsController.php
app/Http/Resources/ProjectResource.php
app/Project.php
composer.json
composer.lock
package-lock.json
routes/api.php

- Add Spatie Ray
- Add basic API routes
- Add debt score accessor to Project
- Add API resource for Projects
- Add forPackagist scope
Co-Authored-By: Tom Witkowski <dev@gummibeer.de>

Take first steps toward headless API

---

.github/workflows/lint.yml
.github/workflows/run-tests.yml
composer.json
composer.lock

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v8.83.5` branch.
- Checkout the `shift-ci-v8.83.5` branch
Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

Laravel 8.83.5 Shift

---

composer.json
composer.lock

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v8.83.9` branch.
- Checkout the `shift-ci-v8.83.9` branch
Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

Laravel 8.83.9 Shift

---

composer.json
composer.lock

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v8.83.16` branch.
- Checkout the `shift-ci-v8.83.16` branch

Laravel 8.83.16 Shift

---

package-lock.json
package.json
resources/ts/components/GitHubItem.vue

This PR fixes an issue when running `npm run dev` or `npm run prod`:
```
Compiled with some errors in 7.88s
ERROR in /Users/anthony/Sites/ozzie/resources/ts/components/GitHubItem.vue.ts
4:7-13
[tsl] ERROR in /Users/anthony/Sites/ozzie/resources/ts/components/GitHubItem.vue.ts(4,8)
TS1192: Module '"/Users/anthony/Sites/ozzie/resources/ts/Pages/Layout.vue"' has no default export.
```

Fix frontend build 

---

app/Console/Commands/FetchProjectStats.php
app/GitHub/Repository.php

Check archived status when fetching project stats.

---

composer.lock
package-lock.json

This PR updates both Composer and NPM dependencies.

Update Composer and NPM dependencies

---

composer.json
composer.lock
package-lock.json

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.13.2` branch.
- Checkout the `shift-ci-v10.13.2` branch

Laravel 10.13.2 Shift

---

app/Console/Commands/CreateProjectSnapshots.php
app/Console/Commands/FetchGitHubProjects.php
app/Console/Commands/FetchProjectStats.php
composer.json

This PR rebuilds the project list cache after fetching to speed up initial load times on the first fetch of the day.

Cache project list after fetch

---

app/Http/Resources/ProjectResource.php

This PR fixes an issue with the new maintainers.
Maintainers are now a relationship on the Project models.  The relationship brings in all the maintainer model info.  I puck out the username to send to the frontend.

Fix maintainers

---

README.md
composer.json
composer.lock
database/seeders/DatabaseSeeder.php
database/seeders/ProjectsSeeder.php
package-lock.json

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.31.0` branch.
- Checkout the `shift-ci-v10.31.0` branch

Laravel 10.31.0 Shift

---

composer.lock

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.37.3` branch.
- Checkout the `shift-ci-v10.37.3` branch

Laravel 10.37.3 Shift

---

app/Http/Middleware/RedirectIfAuthenticated.php
composer.json
composer.lock

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v10.39.0` branch.
- Checkout the `shift-ci-v10.39.0` branch

Laravel 10.39.0 Shift

---

.github/workflows/run-tests.yml
composer.json
composer.lock
config/inertia.php
database/factories/ProjectFactory.php
tests/Feature/PublicRoutesTest.php
tests/Pest.php

- onboards Pest
- adds tests for `projects.index` , `projects.show`, `issue.show` and `pull-request.show` 
- fixes the inertia config around `page_paths`

Adds test to the public facing routes

---

app/Remotes/Packagist/Package.php

Adds a connection timeout check handling scenarios when packagist stalls out

Adds timeout exception handling

---

app/Remotes/Packagist/Package.php

Refactors retry handling and sets retrying behavior to not throw.
- if its a timeout error, we'll retry the http request
- we also pass the 4th arg as `false` as to not throw on error

Tweaks retry handling
