- app/Http/Controllers/DashboardController.php
- projects.json
This PR does two things:
- Add `jigsaw-site` to the projects list in `projects.json`
- Sort the collection of projects pulled from this file, so that scrolling through the dashboard page has them listed in alphabetical order (this doesn't change the table being sorted by debt score)
> Sort projects on dashboard and add jigsaw-site project

- app/Http/Controllers/DashboardController.php
- app/Project.php
- projects.json
- resources/views/dashboard.blade.php
This PR changes the `maintainer` string to a `maintainers` array throughout the app, addressing #3.
The issue also suggested implementing a "main" person designation but I didn't include that here; I figured it's safe to assume the first person in the list is the primary maintainer for now.
> Add support for multiple maintainers

- resources/views/dashboard.blade.php
"💩 in a group" - credit goes to Marje.
> Significantly improve site wording.

- app/Http/Controllers/DashboardController.php
- app/Project.php
- resources/views/dashboard.blade.php
This PR adds a button to the top of the dashboard during the month of October, linking [to these search results](https://github.com/search?o=desc&q=label%3Ahacktoberfest+is%3Aopen+type%3Aissue+user%3Atightenco&s=created&type=Issues). It also adds a `hacktoberfest` label count/link to each project's row in the table. Unrelated: I also removed some unnecessary apostrophes in the column titles.
Fixes #16 (with a little pumpkin or a ghost or something, as requested 😄)
> Add stats/links for Hacktoberfest 🎃

- app/Console/Commands/OutputStats.php
This PR updates the stats CLI output to use a table format (condensing it significantly) and adds some score-based color coding, like the Slack message.
before:
after:
> Use a table to format CLI stats

- app/Notifications/SendOzzieStats.php
- composer.json
- composer.lock
This PR re-formats the Slack stats output using Slack's [Block Kit API](https://api.slack.com/block-kit) and the [nathanheffley/laravel-slack-blocks](https://github.com/nathanheffley/laravel-slack-blocks) package, condensing the size of the message. See #23 for more details.
Screenshots:
Fixes #23.
> Use Block Kit to shorten the Slack stats output

- app/GitHub/Dto/Issue.php
- app/GitHub/Dto/Pr.php
This PR fixes the following errors by defining the `$active_lock_reason` field, which is presumably new:
```
Public properties `active_lock_reason` not found on App\GitHub\Dto\Pr
Public properties `active_lock_reason` not found on App\GitHub\Dto\Issue
```
> Fix Dto errors by defining $active_lock_reason

- README.md
- app/Notifications/SendOzzieStats.php
I missed an `sprintf` in the original Slack text-only URL output, so this PR adds it and makes some minor changes to the README for consistency.
> Add missing sprintf and clean up README

- resources/views/components/debt-table.blade.php
- resources/views/dashboard.blade.php
This PR fixes #36 by converting the projects table from divs & lists to a `<table class="table-auto">` and adding `overflow-x-scroll` to the main page div.
Before:
After:
> Convert projects to a <table>, fix mobile view

- app/Project.php
Exclude PRs in draft status from the debt score, since we're already excluding those labeled `in-progress`.
> Ignore draft PRs in debt score, like `in-progress`

- projects.json
This PR updates the maintainers to match the latest version of our internal list, and alphabetizes the list of projects. It also renames `version-check` to `checkmate`.
@mattstauffer would you like to remove any of the projects that are only assigned to you?
- Confomo
- Giscus
- Gistlog
- Mailthief
- Quicksand
> Update projects and maintainers list

- app/Project.php
The following code is intended to hide any issue/pr that is labeled as 'in progress'. Notice the hyphen.
This PR removes the hyphen so that the label is correctly matched. 
```php
public function issues()
{
return $this->issues->reject(function ($issue) {
return ! empty($issue->labels)
&& collect($issue->labels)->contains('name', 'in-progress');
});
}
```
Note that:
- there are a few projects on Ozzie that do not use the 'in progress' label. Maybe all projects should start using them 🤷 .
- There are some projects that do use the label but on issues/prs that are years old. I'm not sure hiding those is the best idea 🤷 .
For now, maybe the best idea is to accept the PR so that the app functions as designed but maybe
the use of the label should be adopted on all projects or not used at all.
> Correctly hide Issues/prs that are labeled 'in progress'.

- app/GitHub/Dto/Branch.php
- app/GitHub/Dto/Issue.php
- app/GitHub/Dto/Label.php
- app/GitHub/Dto/Pr.php
- app/GitHub/Dto/User.php
Currently, `spatie/data-transfer-object` throws an exception if it encounters a field in the data returned by Github that is not explicitly defined in Ozzies DTOs. This is problematic as GitHub periodically adds new fields to their API.
This PR relaxes that behavior as it is good enough that Ozzie defines the fields it needs and ignores anything else.
**Note:** on 17-JUL-2020, I accessed Ozzie and saw the standard Laravel '500 | Server Error' page. I can't access the production server to see what was happening so I checked my local dev environment. I discovered a new field `performed_via_github_app` was coming back from Github and caused the above error. 
Hopefully, this is what is happening in production :shrug:
> Fix "Public property <PROPERTY> not found" exception.

- app/GitHub/Dto/Issue.php
- app/GitHub/Dto/Label.php
- app/GitHub/Dto/Pr.php
- app/GitHub/Dto/User.php
As discussed [here](https://github.com/tightenco/ozzie/pull/49#issuecomment-660395477), this PR removes fields from the GitHub DTOs that Ozzie does not use.
> Remove unused properties from GitHub DTOs.

- app/Console/Commands/OutputStats.php
Came across Ozzie today and thought it might be useful, so started to play around with it locally.  I noticed that the console output of the projects didn't include namespace, which might be helpful if you had multiple namespaces used (though I appreciate it was intended for the tighten namespace), and gives it a consistent project name output as the web side of things.
Thanks for your consideration!
> Consistency with the output on the web side of things

- .env.example
- config/app.php
- resources/views/components/debt-table.blade.php
- resources/views/dashboard.blade.php
This pull request implements the change I suggested in #69.
Instead of `APP_ORG` being displayed in the title of the page, it is used as the name of the Github organisation. It also no longer hard codes the `tighten` Github username into the `Hacktoberfest is here!` URL for searching issues.
Let me know if you have any questions or if I missed anything.
> Update the uses of APP_NAME and APP_ORG

- .github/workflows/lint.yml
- .github/workflows/run-tests.yml
- app/Remotes/Packagist/Package.php
- composer.json
- composer.lock
Within production Ozzie should run on the current and last LTS versions of Ubuntu as these are the most common Laravel deployment servers. It should also run on the currently supported versions of PHP. It should also run on macOS and Windows since it should work on developer workstations.
With that in mind this PR updates the GitHub test workflow to run tests on every combination of:
- PHP 7.4
- PHP 8+
- Ubuntu 20.04
- Ubuntu 18.04
- Windows Server 2019
- macOS Catalina 10.15.
The lint workflow also receives a minor update so that the PHP extensions and composer installation commands are common across workflows.
**The story behind the PR...**
I found a nasty composer issue that was causing the [Port Ozzie to Inertia PR](https://github.com/tighten/ozzie/pull/93) to fail the GitHub test …
> Test Ozzie on multiple Operating Systems and PHP versions

- .github/workflows/lint.yml
- .github/workflows/run-tests.yml
The `run-test.yml` workflow is failing due to unsatisfiable composer package dependencies. Specifically, package versions in `composer-lock.json` that are incompatible with the PHP version of the currently running container. 
Running `composer update` instead of `composer install` during a fresh installation first upgrades/downgrades  any packages as appropriate before automatically executing a `composer install`.
**Alternative Options**
We could remove `package-lock.json` from version control.
fixes #102 (failing workflows)
> Fix failing composer installations

- README.md
- database/seeds/ProjectsSeeder.php
Make it possible to re-run the seeder when you change the `projects.json` file.
This comes in handy when you don't want to lose the snapshots of the pre-existing projects that you are already tracking.
I tried to keep the change as small as possible to make reviewing a lot easier ;)
> Improve seeder

- app/Http/Resources/Api/ProjectResource.php
Sauce relies on Ozzie for syncing with and displaying information about internal projects (20% projects). We need the `is_hidden` key available so we can display active only internal projects.
> Add `is_hidden` Attribute To Project Resource

- .github/workflows/run-tests.yml
This PR updates the GH test action to drop `ubuntu-18.04`:
https://github.com/actions/runner-images/issues/6002
> Update tests to drop deprecated `ubuntu-18.04`

- projects.json.dist
This PR removes `gistlog.co` and `novapackages.com`.
> Remove `gistlog.co` and `novapackages.com`

- app/Cache/CachedProjectList.php
- app/Console/Commands/FetchProjectStats.php
- app/Notifications/SendOzzieStats.php
- app/Project.php
This PR makes `is_hidden` default to the current database value.
The daily `projects:fetch` command syncs projects from the GitHub organization.  Without this change, the only way to hide projects is to archive them in GitHub.  Making `is_hidden` default to the current database value allows us to mark projects as hidden in the database regardless of them being archived in GitHub. 
These hidden projects will continue to be updated in case they become visible.
> Make `is_hidden` sticky

- app/Console/Commands/FetchProjectStats.php
- app/Remotes/Packagist/Package.php
- tests/Feature/FetchProjectStatsTest.php
- Tests `stats:fetch` command 
- Mocks HTTP and GitHub requests
- Reports if 500 on Packagist
- We try to fetch on all packages, regardless if they exist or not in packagist.org, which feel odd
- If packagist.org, for whatever reason, fails to report, we would no longer overwrite download counts
reference 
- #89 
- #88
> Test the `stats:fetch` command, and report if Packagist download count fails

- app/GitHub/Repository.php
- package-lock.json
- package.json
- postcss.config.js
- resources/views/app.blade.php
- vite.config.js
- bumps `vite` to `5.0`, `laravel-vite` to `1.0` and `@vitejs/plugin-vue` to `5.0`
- refactors node build tools to esm, due to vite
- minor deletion of empty import
> Update Vite to 5.0

- package-lock.json
- package.json
This PR updates vite to 5.0.13 and runs `npm audit fix`
https://github.com/tighten/ozzie/pull/273
> Update vite and run `npm audit fix`

- app/Cache/CachedProjectList.php
- app/Console/Commands/FetchProjectStats.php
- app/Http/Resources/ProjectResource.php
- app/OrgSlack.php
- tests/Feature/CreateProjectSnapshotsTest.php
- tests/Feature/FetchGitHubProjectsTest.php
- tests/Feature/FetchProjectStatsTest.php
- tests/Feature/GetProjectsTest.php
- tests/Feature/OutputStatsTest.php
- tests/Feature/SendStatsToSlackTest.php
- tests/Feature/ShowProjectTest.php
Adds the following test cases:
Commands:
- `CreateProjectSnapshotsTest`
- `FetchGitHubProjectsTest`
- `FetchProjectStatsTest`
- `OutputStatsTest`
- `SendStatsToSlackTest`
API routes:
- `GetProjectsTest`
- `ShowProjectTest`
Also makes some minor changes:
- Removes an unreachable return statement in `CachedProjectList`.
- Re-keys the issues and pull requests collections in `FetchProjectStats` to make it easier to assert their values when testing.
- Changes how we avoid wrapping in the `ProjectResource` because the previous approach actually removes wrapping from `JsonResource` affecting all json resources.
- Implements the `getKey()` method on the `OrgSlack` notifiable to allow testing using `Notification::fake()`.
---
All test cases passing with these changes and linter is green. Happy to …
> Adds test coverage for commands and project api routes

- .env.example
- .gitignore
- README.md
- composer.json
- composer.lock
- docker-compose.yml
- vite.config.js
- Onboards sails deps and out of the box `docker-compose.yml`
- Tweaks the vite config to play nice in none valet environments
- Updates readme and gitignore 
- Any particular reason https was strict? given sails lets the hostname up in the air, if we want to approach it from our end we could explore adding caddy to the mix
- Given sail out of the box has strong opinions around the `.env` database config, wasn't 100% if it was worth highlighting on the `.env.example` or in the actual readme under the sail instructions
- #91
- #92
> Onboarding Sail (docker)
